export const MAX_SCC_COLORS = 30;

export const SCC_PALETTE: { bg: string; border: string; text: string }[] = [
  { bg: "bg-emerald-600", border: "border-emerald-400", text: "text-white" },
  { bg: "bg-amber-600", border: "border-amber-400", text: "text-white" },
  { bg: "bg-rose-600", border: "border-rose-400", text: "text-white" },
  { bg: "bg-sky-600", border: "border-sky-400", text: "text-white" },
  { bg: "bg-violet-600", border: "border-violet-400", text: "text-white" },
  { bg: "bg-teal-600", border: "border-teal-400", text: "text-white" },
  { bg: "bg-orange-600", border: "border-orange-400", text: "text-white" },
  { bg: "bg-pink-600", border: "border-pink-400", text: "text-white" },
  { bg: "bg-lime-600", border: "border-lime-400", text: "text-white" },
  { bg: "bg-cyan-600", border: "border-cyan-400", text: "text-white" },
  { bg: "bg-indigo-600", border: "border-indigo-400", text: "text-white" },
  { bg: "bg-fuchsia-600", border: "border-fuchsia-400", text: "text-white" },
  { bg: "bg-red-600", border: "border-red-400", text: "text-white" },
  { bg: "bg-yellow-600", border: "border-yellow-400", text: "text-white" },
  { bg: "bg-green-600", border: "border-green-400", text: "text-white" },
  { bg: "bg-blue-600", border: "border-blue-400", text: "text-white" },
  { bg: "bg-purple-600", border: "border-purple-400", text: "text-white" },
  { bg: "bg-amber-700", border: "border-amber-500", text: "text-white" },
  { bg: "bg-rose-500", border: "border-rose-300", text: "text-white" },
  { bg: "bg-sky-500", border: "border-sky-300", text: "text-white" },
  { bg: "bg-emerald-500", border: "border-emerald-300", text: "text-white" },
  { bg: "bg-teal-500", border: "border-teal-300", text: "text-white" },
  { bg: "bg-violet-500", border: "border-violet-300", text: "text-white" },
  { bg: "bg-orange-500", border: "border-orange-300", text: "text-white" },
  { bg: "bg-pink-500", border: "border-pink-300", text: "text-white" },
  { bg: "bg-indigo-500", border: "border-indigo-300", text: "text-white" },
  { bg: "bg-cyan-500", border: "border-cyan-300", text: "text-white" },
  { bg: "bg-lime-700", border: "border-lime-500", text: "text-white" },
  { bg: "bg-red-500", border: "border-red-300", text: "text-white" },
  { bg: "bg-green-500", border: "border-green-300", text: "text-white" },
];
